spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://112.91.140.229:34307/health?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: actuser
          password: actuser0605
      druid:
        initial-size: 20
        max-active: 60
        min-idle: 20
        max-wait: 30000
  redis:
    #host: 175.178.234.59
    #port: 6637
    host: redis
    port: 6379
    password: aisn123456
    database: 2
# minio
minio:
  endpoint: http://172.16.0.8:10000
  access-key: actuser
  access-secret: actuser0605
  bucket-name: qf-pan
  bucket-name-public: qf-public
  avatar-bucket-name: avatar
  health-bucket-name: actfiles
  pre: https://act.dyjk.cn/actfiles/
# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 返回map时true:当查询数据为空时字段返回为null,false:不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

weixin:
  corpid: wx5d90ab232b0113b3
  corpsecret: NukEJRDdUcd4IMTsZzHrHGnzt9oz_GI3LXCY8o1in1I
  url: https://qyapi.weixin.qq.com/cgi-bin/gettoken
  userinfoUrl: https://qyapi.weixin.qq.com/cgi-bin/auth/getuserinfo
  deptUrl: https://qyapi.weixin.qq.com/cgi-bin/department/list
  userUrl: https://qyapi.weixin.qq.com/cgi-bin/user/simplelist
  ticketUrl: https://qyapi.weixin.qq.com/cgi-bin/ticket/get
  mediaUrl: https://qyapi.weixin.qq.com/cgi-bin/media/get
  AppID: wx0c6183a526a5c605
  secret: 446ba2a5ab1a90da51e76b7c883e41d1
  weixinTokenUrl: https://api.weixin.qq.com/cgi-bin/stable_token
  weixinTicketUrl: https://api.weixin.qq.com/cgi-bin/ticket/getticket
  weixinmediaUrl: https://api.weixin.qq.com/cgi-bin/media/get

duanxin:
  url: https://oa.dyjk.cn/prod-api/interface/tjapi/gettoken
  user: actuser
  password: actuser0605
  sendUrl: https://oa.dyjk.cn/prod-api/message/messageTemplate/sendSMSMessageCode
  verifyUrl: https://oa.dyjk.cn/prod-api/message/messageTemplate/sendSMSMessageValiedate